Update gh action

diff --git a/.github/workflows/azure-static-web-apps-gray-plant-06f4a0003.yml b/.github/workflows/azure-static-web-apps-gray-plant-06f4a0003.yml
--- a/.github/workflows/azure-static-web-apps-gray-plant-06f4a0003.yml
+++ b/.github/workflows/azure-static-web-apps-gray-plant-06f4a0003.yml
@@ -19,6 +19,26 @@ jobs:
         with:
           submodules: true
           lfs: false
+
+      # Clean npm cache to avoid potential issues with corrupted tarballs
+      - name: Clean npm cache
+        run: npm cache clean --force
+
+      # Verify the integrity of the tarball file
+      - name: Verify tarball integrity
+        run: |
+          if [ -f "/github/rt-client-0.4.6.tgz" ]; then
+            tar -tzf /github/rt-client-0.4.6.tgz
+          else
+            echo "Tarball not found, please check the path or regenerate the tarball."
+            exit 1
+          fi
+
+      # Install npm dependencies
+      - name: Install dependencies
+        run: npm install
+
+      # Build and Deploy
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
